### ISSUE TITLE
Incompatible with Xaero's Minimap Fair-play Edition

### ISSUE THREAD

**Issue by niraqw** [duely/w2w#12]
Waystones2Waypoints requires the normal version of Xaero's minimap, and is thus incompatible with the Fair-play Edition (or just using Xaero's World Map standalone).

**Comment by noobanidus** [comment]
Ah, that's fair, I need to check dependencies again.

**Comment by LordPhrozen** [comment]
Any update on that :( ?

**Comment by noobanidus** [comment]
As Xaero's has no actual API and there's regular code changes that make it difficult to keep up-to-date or maintain backwards compatibility, I'm either going to have to talk to Xaero about an API or retire this mod. Unfortunately, I think the latter is my preferred option at the minute, as my plate is pretty full.
