### ISSUE TITLE
Check functionality with Waystones/Xaero's

### ISSUE THREAD

**Issue by Nicknaem** [duely/w2w#13]
am I missing something or is there a bug, Im on 1.16.5, installed theese versions of mods, and it just doesnot work
![image](https://user-images.githubusercontent.com/55950404/128838019-065a925b-1c65-44e6-88e2-be0119693cfc.png)

well I loaded older version of waypoints released in 2020 Waystones_1.16.3-7.3.1, It does add waypoints on minimap and xaeros worldmap, but the big problem is that whenever I destroy waypoint or remove it from waystones hud menu, they arenot being removed from map, wasnt this function implemented?

waystoned2waypoints is awesome mod, please update it so it works normally as expected

**Comment by noobanidus** [comment]
I presume something changed again.

**Comment by Nicknaem** [comment]
> presume

did this mod have functionality to remove waypoints from the map whenever waystones were destroyed or removed from menu? maybe I messed up something

**Comment by noobanidus** [comment]
> > presume
> 
> did this mod have functionality to remove waypoints from the map whenever waystones were destroyed or removed from menu? maybe I messed up something

Nope, never did.

**Comment by Nicknaem** [comment]
> > > presume
> > 
> > 
> > did this mod have functionality to remove waypoints from the map whenever waystones were destroyed or removed from menu? maybe I messed up something
> 
> Nope, never did.

I if doesn't need much effort to implement it would be really great to have that functionality, especially in 1.16.5 lots of people use waystones and xaeros map

**Comment by noobanidus** [comment]
It would take way too much effort to implement, sorry.

**Comment by Nicknaem** [comment]
thanks for quick responses
