### ISSUE TITLE
crash with latest XaeroMinimap

### ISSUE THREAD

**Issue by LlubNek** [duely/w2w#5]
When right clicking a waystone, Minecraft crashes with the following error:

```
java.lang.NoSuchMethodError: xaero.minimap.XaeroMinimap.getWaypointsManager()Lxaero/common/minimap/waypoints/WaypointsManager;
	at noobanidus.mods.w2w.WaypointHandler.makeWaypoint(WaypointHandler.java:16) ~[?:?] {re:classloading}
	at noobanidus.mods.w2w.WaystonesHandler.onWaystoneActivated(WaystonesHandler.java:10) ~[?:?] {re:classloading}
	at noobanidus.mods.w2w.Waystones2Waypoints$$Lambda$5069/1213982530.accept(Unknown Source) ~[?:?] {}
```

w2w-1.15.2-0.0.0.1.jar
Waystones_1.15.2-6.0.2.jar
Xaeros_Minimap_20.16.0.1_Forge_1.15.2.jar
forge-31.2.31
minecraft 1.15.2

[latest.log](https://github.com/noobanidus/w2w/files/4925844/latest.log)
[crash-2020-07-15_10.19.54-client.txt](https://github.com/noobanidus/w2w/files/4925845/crash-2020-07-15_10.19.54-client.txt)

**Comment by noobanidus** [comment]
Ah, that is unfortunate, it looks like Xaero has changed how things work.

I'll need to reconsider how I want to implement this, as I know there are some issues with Waystone events triggering in a weird fashion. I'll try to look into it ASAP.

**Comment by greysondn** [comment]
Just a quick "Yes, me too!"

If you want extra logs or an extra set of hands to test, I'm usually "around". Otherwise, no specific hurry.

Or if you'd like me to act like a normal commenter-slash-user, "PLS MUH MOD PCK NEEDS DIS OMG WHYYYYYYYY MEEEEEEEE"

;) Be well. It's a great mod. I'll be ecstatic when/if it's fixed again.

**Comment by noobanidus** [comment]
Hopefully the latest update resolves this issue.

**Comment by greysondn** [comment]
Ah, geez. Any chance we can get this for 1.12, @noobanidus ?

**Comment by noobanidus** [comment]
Ah bugger, I didn't realise the codebase had changed that significantly. @greysondn can you open a new issue for 1.12?
