### ISSUE TITLE
[1.12.2] Crashes game when clicking/placing waystone

### ISSUE THREAD

**Issue by AngleWyrm10** [duely/w2w#8]
Tested with:
Waystones2Waypoints v1.1.1 for 1.12.2
Waystones  v4.1.0
Xaero's minimap v20.20.0
JEI 4.15.0.297

**Comment by noobanidus** [comment]
Please provide the crash log.

**Comment by AngleWyrm10** [comment]
[Link to crash log](https://paste.ee/p/nZ317)

**Comment by noobanidus** [comment]
Please update to 1.2.1 which has already been released as a fix for this.
